name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'Emitron/.swiftlint.yml'
      - 'Emitron/**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Install Swiftlint
      #   run: brew install swiftlint

      - name: Run Swiftlint
        run: swiftlint version
        # run: swiftlint --config Emitron/.swiftlint.yml
